import { useRouter } from "next/router";
import useSWR from "swr";
import * as cheerio from "cheerio";
import Head from "next/head";
import Image from "next/image";
import { Nabla } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const Post = () => {
  const router = useRouter();
  const { pid } = router.query;
  const fetcher = (url) => fetch(url).then((res) => res.json());

  const { data, error } = useSWR(`../api/staticevent?slug=${pid}`, fetcher);
  //Handle the error state
  if (error) return <div>Failed to load</div>;
  //Handle the loading state
  if (!data) return <div>Loading...</div>;

  const $ = cheerio.load(data);
  const jsonRaw = $("script[type='application/ld+json']")[0].children[0].data;
  const event = JSON.parse(jsonRaw);

  return (
    <>
      <Head>
        <title>Agenda du numérique poitevin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <h1 className={`${styles.h1}`}>Agenda du numérique</h1>
        <h2 className={styles.h2}>{event.name}</h2>
        <p>
        {event.description}
        </p>
      </main>
    </>
  );
};

export default Post;
