import Head from 'next/head'
import Image from 'next/image'
import { Nabla } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import Hometable from '../components/hometable';

const nabla = Nabla({
  weight:'400',
  subsets:['latin']
})


export default function Home() {
  return (
    <>
      <Head>
        <title>Agenda du numérique poitevin</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
             </Head>
      <main className={styles.main}>
       <h1 className={`${styles.h1} ${nabla.className}`} >Agenda du numérique</h1>
       <h2 className={styles.h2}>Evénements à venir</h2>
       <Hometable />
       

      </main>
    </>
  )
}
