on: [push,workflow_call]

jobs:
  build:
    name: Create compil events file
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3      
      # with: 
      #   node-version: '16' 
    - name: Node Install
      run: npm ci
    - name: run compil Cobalt
      run: node scripts/compilCobalt.js
    - name: run compil Pwn
      run: node scripts/compilPwn.js
    - name: run compil EMF
      run: node scripts/compilEMF.js
    - name: run compil global
      run: node scripts/compil.js
    - name: Commit files
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add --all
        if [ -n "$(git status --porcelain)" ]; then
          git commit -am "Update compil file"
        fi
        git push
