on: push

jobs:
  build:
    name: Test workflow_dispatch
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3      
      with: 
        node-version: '16' 
    - name: Node Install
      run: npm ci
    - name: run compil
      run: node scripts/compil.js
